### PR TITLE
wasm-4: Add WASM-4 Content

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by RobLoach** [comment]
@aduros Can we distribute Dodgebacll, Meteoroids, Minesweeper, Racer, Snake and Watris through the RetroArch Content Downloader? Do you happen to know the license assosidated with those games?

**Comment by RobLoach** [comment]
We'll have to reach out to the individual authors of these wasm carts. For now I think we're good to distribute Bruno's own ones from https://github.com/aduros/wasm4/tree/main/site/static/carts .... Sound Demo, and Watris may be a good safe start.

**Comment by fpscan** [comment]
> We'll have to reach out to the individual authors of these wasm carts. For now I think we're good to distribute Bruno's own ones from https://github.com/aduros/wasm4/tree/main/site/static/carts .... Sound Demo, and Watris may be a good safe start.

Hmm, is it what Aduros said or each content has it's own licence(?)

**Comment by RobLoach** [comment]
We are just careful about distributing content without author permission 👀... I've reached out to aduros on it.

**Comment by RobLoach** [comment]
Pushing the first two carts over at https://github.com/libretro/libretro-content/pull/28

**Comment by aduros** [comment]
Hey folks, we can probably add more soon, I just wanted to reach out to the cart developers for permission in good faith. Most of the developers I've talked to are excited about it.

By the way, we're running a game jam right now, at the end of it we should have a lot more games to possibly showcase!

**Pull request closed without merging**
