### PR TITLE
gba: add Apotris

### PR DESCRIPTION
**Pull request by abouvier**
Awesome GPL3-licensed Tetris-like game from https://akouzoukos.com/apotris/.

### CODE REVIEW

**Comment by RobLoach** [comment]
Looking through the FAQ, it looks like the source was taken down due to a DMCA notice:
https://github.com/akouzoukos/apotris/wiki/FAQ#where-is-the-source-code

Considering this, while I do believe this is the best Tetris implementation on pretty much any platform, I don't think we should distribute it ourselves.

**Comment by abouvier** [comment]
The version 3.4.5 is [referenced](https://datomatic.no-intro.org/index.php?page=show_record&s=23&n=2997) by No-Intro. It should probably be updated by someone :p

The source code is [downloadable](https://akouzoukos.com/files/apotris-v3.4.6.zip) on the official website.

**Comment by hizzlekizzle** [comment]
Ah, presumably they're hosting the source outside of the USA. Unfortunately, most of our hosting is USA-based and therefore reachable by DMCA.

As an aside, I'm surprised that a court found their game mechanics to be copyright-able. I had thought mechanics specifically _weren't_:
```
-the design and movement of the playing pieces, including the downward, lateral and rotating movement

-the bright colors of the playing pieces

-the dimensions of the playing field, longer than it is wide

-the appearance of ghost or shadow pieces

-the display of the next piece to fall
```

**Comment by RobLoach** [comment]
Just added a homebrew entry in libretro-database:
https://github.com/libretro/libretro-database/commit/5887b82733c3b69aa24cbe7a3afb7eabad7e2d7b

It'll allow it to be scanned, and we can add any other metadata we want in there. While we can't distributed it, we can make it easier to detect :+1:

**Pull request closed without merging**
